language: go
go:
  - 1.10.x
  - tip
go_import_path: github.com/t-pwk/go-fibonacci
before_script:
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/mattn/goveralls
script:
  - go test -v -covermode=count -coverprofile=coverage.out ./...
  - $GOPATH/bin/goveralls -service=travis-ci

